<a href="https://colab.research.google.com/github/bhaskarverma1/-CodEvo-Solutions-AI-/blob/main/task-imagerecognitionusingCNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, Dropout
from tensorflow.keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report
# Load CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize pixel values to be between 0 and 1
x_train = x_train / 255.0
x_test = x_test / 255.0

# Convert class vectors to binary class matrices
num_classes = 10
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)
model = Sequential()

# Convolutional layers
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

# Flatten the output
model.add(Flatten())

# Dense layers
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# Train the model
history = model.fit(x_train, y_train, batch_size=32, epochs=20, validation_data=(x_test, y_test))
# Evaluate the model on test data
test_loss, test_acc = model.evaluate(x_test, y_test)
print('Test accuracy:', test_acc)

# Confusion matrix
predicted_classes = model.predict(x_test)
predicted_classes = np.argmax(predicted_classes, axis=1)
true_classes = np.argmax(y_test, axis=1)
confusion_mtx = confusion_matrix(true_classes, predicted_classes)
print('Confusion Matrix:\n', confusion_mtx)
print('Classification Report:\n', classification_report(true_classes, predicted_classes))
# Save the model
model.save('cifar10_cnn_model.h5')

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 6s 0us/step


/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/20
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 315s 200ms/step - accuracy: 0.3514 - loss: 1.7509 - val_accuracy: 0.5948 - val_loss: 1.1192
Epoch 2/20
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 319s 204ms/step - accuracy: 0.5967 - loss: 1.1404 - val_accuracy: 0.6932 - val_loss: 0.8827
Epoch 3/20
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 313s 198ms/step - accuracy: 0.6648 - loss: 0.9494 - val_accuracy: 0.7027 - val_loss: 0.8515
Epoch 4/20
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 325s 200ms/step - accuracy: 0.7027 - loss: 0.8475 - val_accuracy: 0.7315 - val_loss: 0.7858
Epoch 5/20
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 321s 199ms/step - accuracy: 0.7272 - loss: 0.7807 - val_accuracy: 0.7416 - val_loss: 0.7504
Epoch 6/20
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 313s 200ms/step - accuracy: 0.7510 - loss: 0.7166 - val_accuracy: 0.7622 - val_loss: 0.6964
Epoch 7/20
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 322s 200ms/step - accuracy: 0.7643 - loss: 0.6777 - val_accuracy: 0.7547 - val_loss: 0.7092
Epoch 8/20
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 324s 202ms/step - ac

Confusion Matrix:
 [[848   7  26  10   7   6   8   9  46  33]
 [ 11 854   2   5   3   2   6   1  24  92]
 [ 73   1 626  49 108  42  63  15  14   9]
 [ 21   3  45 606  63 138  71  16  13  24]
 [ 17   3  25  47 827  19  29  23   6   4]
 [  7   2  24 160  50 681  30  25  10  11]
 [  8   2  18  31  34   9 885   1   9   3]
 [ 15   1  27  37  64  42   9 780   8  17]
 [ 40  12   7   7   6   1   8   1 900  18]
 [ 19  40   2   9   4   2   2   6  25 891]]
Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.85      0.82      1000
           1       0.92      0.85      0.89      1000
           2       0.78      0.63      0.69      1000
           3       0.63      0.61      0.62      1000
           4       0.71      0.83      0.76      1000
           5       0.72      0.68      0.70      1000
           6       0.80      0.89      0.84      1000
           7       0.89      0.78      0.83      1000
           8       0.85      0.90      